name: Build
on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  build:
    name: Running TSLint and Jest
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Install
        run: yarn

      - name: Lint
        run: npm run lint:tslint

      - name: Test
        run: npm run ci:test
